on:
  push:
    paths:
      - 'version/searx.txt'

name: searx
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build searx
        run: |
          VER=$(wget -qO- https://api.github.com/repos/searx/searx/tags | grep 'name' | cut -d\" -f4 | head -1)
          git clone https://github.com/searx/searx searx
          pushd searx || exit 1
          docker build -t ${{ secrets.DOCKER_USERNAME }}/searx:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/searx:latest
          popd || exit 1
          rm -rf searx
      
      - name: Build filtron
        run: |
          git clone https://github.com/asciimoo/filtron filtron
          rm -rfv filtron/Dockerfile && cp -rf src/searx/filtron/Dockerfile filtron/Dockerfile
          pushd filtron || exit 1
          wget -O rules.json https://raw.githubusercontent.com/bolucat/searx-docker/master/rules.json
          docker build -t ${{ secrets.DOCKER_USERNAME }}/filtron:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/filtron:latest
          popd || exit 1
          rm -rf filtron
      
      - name: Build morty
        run: |
          git clone https://github.com/asciimoo/morty morty
          rm -rfv morty/Dockerfile && cp -rf src/searx/morty/Dockerfile morty/Dockerfile
          pushd morty || exit 1
          docker build -t ${{ secrets.DOCKER_USERNAME }}/morty:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/morty:latest
          popd || exit 1
          rm -rf morty