on:
  push:
    paths:
      - 'version/trojan-r.txt'

name: trojan-r
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Set env
        run: |
          echo "VERSION=$(cat "version/trojan-r.txt" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash
      
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt,clippy,rls

      - name: Build
        run: |
          sudo apt install -y git wget gcc g++ make automake musl-tools
          cp src/build/trojan-r.sh $PWD/trojan-r.sh && chmod +x trojan-r.sh && ./trojan-r.sh
       
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./release/*
            
  push:
    needs: build
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Set env
        run: |
          echo "VERSION=$(cat "version/trojan-r.txt" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Get Dockerfile
        run: |
          cp src/trojan-r/* $PWD
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build latest
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/trojan-r:latest
            ${{ secrets.DOCKER_USERNAME }}/trojan-r:${{ env.VERSION }}
           
  test:
     needs: [build,push]
     runs-on: ubuntu-20.04
     steps:
       
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup variables
        run: |
          echo "VERSION=$(cat "version/trojan-r.txt" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Test Docker image
        run: |
          docker run --rm --entrypoint /usr/bin/trojan-r ${{ secrets.DOCKER_USERNAME }}/trojan-r:latest --version
          docker run --rm --entrypoint /usr/bin/trojan-r ${{ secrets.DOCKER_USERNAME }}/trojan-r:${{ env.VERSION }} --version
