on:
  push:
    paths:
      - 'version/watchtower.txt'

name: watchtower
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set Env
        run: |
          echo "GOLANG=$(wget -qO- https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep 'version' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV
          echo "VERSION=$(cat "version/watchtower.txt" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Install Golang
        uses: actions/setup-go@v2
        with: 
          go-version: ${{ env.GOLANG }}

      - name: Start build
        run: |
          cp src/build/watchtower.sh $PWD/watchtower.sh && chmod +x watchtower.sh && ./watchtower.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./release/*

  push:
    needs: build
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set variables
        run: |
          echo "VERSION=$(cat "version/watchtower.txt" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Get Dockerfile
        run: |
          cp src/watchtower/* $PWD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build latest
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/watchtower:latest
            ${{ secrets.DOCKER_USERNAME }}/watchtower:${{ env.VERSION }}

  test:
    needs: [build,push]
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set variables
        run: |
          echo "VERSION=$(cat "version/watchtower.txt" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Test Docker image
        run: |
          docker run --rm --entrypoint /watchtower ${{ secrets.DOCKER_USERNAME }}/watchtower:latest --help
          docker run --rm --entrypoint /watchtower ${{ secrets.DOCKER_USERNAME }}/watchtower:${{ env.VERSION }} --help